all: bsttest avltest splaytest

bsttest: bst/testmain.cpp
	g++ -g -Wall -std=c++11 bst/testmain.cpp -o bsttest

avltest: avl/testmain.cpp
	g++ -g -Wall -std=c++11 avl/testmain.cpp -o avltest

splaytest: splay/testmain.cpp
	g++ -g -Wall -std=c++11 splay/testmain.cpp -o splaytest